version: "3"
services:
  authentiq:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
    ports:
      - "2000:2000"
    command: npm run dev
#    command: sh -c "npm install -g nodemon && npm install && npm run dev "

  authentiq-db:
    image: mongo:4.2.3-bionic
    environment:
      - MONGO_INITDB_DATABASE=authentiq
    volumes:
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./volumes/mongodb.dev:/data/db
      - ./mongoconfig:/data/configdb
